#include "shell.h"

/**
 * signal_handler - function that handle the signal generated by the user to go out of the program
 * @sig: the input signal
 *
 * Return: nothing
 */
void signal_handler(int sig)
{
	write(STDOUT_FILENO, "/n$", 3);
}
